### ISSUE TITLE
Using MitoGraph on windows

### ISSUE THREAD

**Issue by Alecampoy** [vianamp/MitoGraph#15]
Hi, is it posible to use MitoGraph in windows or will be in the future???
Ale

**Comment by vianamp** [comment]
I have a Windows version of MitoGraph compiled by a collaborators. Please send me an email and I can share that with you.

**Comment by w1oves** [comment]
I also hope to get the Windows version of this software. Thank you very much! My email is zhixiangwei@mail.ustc.edu.cn

**Comment by edallort** [comment]
Hi! I also hope to get the Windows version of this software, could it be possible? I thank you very much in advance. here is my email adress eleonora.dallorto@unito.it

**Comment by vianamp** [comment]
MitoGraph v3.1 has now support to Windows 10.
