### ISSUE TITLE
Using mitograph on Macos 15.0 with VTK 9.3.1

### ISSUE THREAD

**Issue by vicky-wang547** [vianamp/MitoGraph#17]
Hi, I am currently using Mitograph on my Mac, and the following errors appear when I try to open it. I think it's the VTK version problem, it looks like mitograph is trying to find 8.2.1 while my VTK is version 9.3.1

Library not loaded: @rpath/libvtkDomainsChemistryOpenGL2-8.2.1.dylib
  Referenced from: <054249A0-A95B-37B7-8618-AB3B49711E81> /Users/vickywang547/Desktop/MitoGraph/MitoGraph 2
  Reason: tried: '/opt/homebrew/Cellar/vtk/9.3.1_2/lib/libvtkDomainsChemistryOpenGL2-8.2.1.dylib' (no such file), '/opt/homebrew/Cellar/vtk/9.3.1_2/lib/libvtkDomainsChemistryOpenGL2-8.2.1.dylib' (no such file), '/libvtkDomainsChemistryOpenGL2-8.2.1.dylib' (no such file), '/usr/local/lib/libvtkDomainsChemistryOpenGL2-8.2.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libvtkDomainsChemistryOpenGL2-8.2.1.dylib' (no such file), '/usr/local/lib/libvtkDomainsChemistryOpenGL2-8.2.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libvtkDomainsChemistryOpenGL2-8.2.1.dylib' (no such file), '/usr/local/lib/libvtkDomainsChemistryOpenGL2-8.2.1.dylib' (no such file), '/usr/lib/libvtkDomainsChemistryOpenGL2-8.2.1.dylib' (no such file, not in dyld cache)
zsh: abort      ./MitoGraph\ 2 -xy 0.064 -z 0.2 -path 

How can I solve this problem?

Thanks a lot!

**Comment by vianamp** [comment]
Hi. MitoGraph was compiled against VTK 8.2. However, you should be able to run it without having any version of VTK installed. Did you compiled it yourself or are you running the binary release that I made available here on Github? You can also try to install the correct VTK version to see if you overcome this problem: `brew install vtk@8.2`.

**Comment by vicky-wang547** [comment]
Thanks for your reply! I downloaded the V3.1 [MitoGraph_OSX12.zip] from github. Also, "brew install vtk@8.2" doesn't work on my computer. It seems to be outdated.

**Comment by vianamp** [comment]
Do you have any other Mac system with an older OS version to try it out? I have never tried to run MitoGraph on anything newer than OSX 12.5.

**Comment by vicky-wang547** [comment]
sorry I don't have any other Mac system with an older OS version, I had just updated my system last week...

**Comment by vianamp** [comment]
I am sorry. I don't have a newer system to test it on.
