### ISSUE TITLE
Error running on Mac 13.5.2

### ISSUE THREAD

**Issue by shanemc11** [vianamp/MitoGraph#18]
I'm trying to run MitoGraph (most recent version) using the sample data and am getting the follow error:

dyld[1449]: Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
  Referenced from: <7D80BFDF-67AB-3666-9A4A-10FDC71123A8> /Users/smcinally/Desktop/MitoGraph/MitoGraph
  Reason: tried: '/System/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file, not in dyld cache), '/Library/Frameworks/Python.framework/Versions/2.7/Python' (no such file)
zsh: abort      ./MitoGraph -xy 0.056 -z 0.2 -path ~/Desktop/MitoGraphTools-master

Any tips on solving this issue?

Thanks

**Comment by vianamp** [comment]
Hi. I believe you are using a MacOS on M series chipset. If so, all you need is to download and install python 2.7. Please use this link to download and install:

https://www.python.org/downloads/release/python-2718/

Then give MitoGraph another try.

**Comment by shanemc11** [comment]
Fantastic! That fixed the error. Thank you for your reply, I really appreciate it.
